// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boxContainer': string;
  'boxContent': string;
  'boxFooter': string;
  'boxHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
