// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Accessory': string;
  'CardBody': string;
  'CardContainer': string;
  'Content': string;
  'Header': string;
  'Icon': string;
}
export const cssExports: CssExports;
export default cssExports;
