// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contextmenu': string;
  'contextmenuBackdrop': string;
}
export const cssExports: CssExports;
export default cssExports;
