// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backdrop': string;
  'modalContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
