// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'DiceButton': string;
  'Module': string;
}
export const cssExports: CssExports;
export default cssExports;
