// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'column': string;
  'container': string;
  'group': string;
  'header': string;
  'plugin': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
