// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Module': string;
  'settingsButton': string;
}
export const cssExports: CssExports;
export default cssExports;
