// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'group': string;
  'groupContent': string;
  'groupHeader': string;
  'simpleeqModule': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
