// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blah': string;
  'component-fader': string;
  'component-knob': string;
  'component-select': string;
  'component-wrapper': string;
  'module': string;
}
export const cssExports: CssExports;
export default cssExports;
