// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pianoroll': string;
  'pianorollBody': string;
  'pianorollContainer': string;
  'playhead': string;
}
export const cssExports: CssExports;
export default cssExports;
