// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'big': string;
  'default': string;
  'huge': string;
}
export const cssExports: CssExports;
export default cssExports;
