// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'default': string;
  'destructive': string;
  'success': string;
  'topbar': string;
  'topbarMenu': string;
  'topbarSuccess': string;
  'transport': string;
}
export const cssExports: CssExports;
export default cssExports;
