// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ControlContainer': string;
  'LabelContainer': string;
  'default': string;
}
export const cssExports: CssExports;
export default cssExports;
