// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boxHeader': string;
  'control': string;
  'formSection': string;
  'pageHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
