// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'default': string;
  'topbar': string;
}
export const cssExports: CssExports;
export default cssExports;
